### ISSUE TITLE
Gap between toggle switch buttons and container

### ISSUE THREAD

**Issue by dtwen** [cgarvis/angular-toggle-switch#64]
We're using angular for an android app. On my Samsung Galaxy S3, there is a 1px-3px gap between the toggle switch and container (see screenshots).  I've tried 3 times to close the gap; As soon as I close one gap on the **off button** a gap will appear on the **off button**.  

Attempt No 1
```css
.toggle-switch .switch-off {
  left: -49%;
}
```

Attempt No 2
```css
.toggle-switch .knob {
  border: none;
}
```

Attempt No 3
```css
.toggle-switch .knob {
  border: none;
}
```

My current CSS: 
```css
     .toggle-switch {
    border: 2px solid #626262;
    float: right;
    }
    .toggle-switch span {
    height: 100%;
    font-size: 12px;
    text-transform: uppercase;
    font-weight: normal;
    }
    .toggle-switch .switch-left {
    color: #fff;
    background: #33b5e5;
    text-transform: uppercase;
    }
    .toggle-switch .switch-right {
    color: #000;
    background: #1e6681;
    text-transform: uppercase;
    }
```

**Any ideas on how to fix it so there's no gap on both buttons? Thanks.**

![galaxy-note3-screenshot-2](https://cloud.githubusercontent.com/assets/2575982/6808914/f23435c6-d224-11e4-92fc-714738c4d500.jpg)
![galaxy-note3-screenshot](https://cloud.githubusercontent.com/assets/2575982/6808915/f238bb6e-d224-11e4-9887-0c47e78b9112.jpg)
